<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>bjl_smtp</artifactId>
	<name>Bringardner Java Library Smtp Implementation</name>
	<groupId>us.bringardner</groupId>
	<version>0.1.0</version>

	<description>This project holds an implementation of an SMTP server usint the BJL Network Framework.</description>
	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.3</version>
					<configuration>
						<source>21</source>
						<target>21</target>
					</configuration>
				</plugin>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>3.3.1</version>
					<executions>
						<execution>
							<id>attach-sources</id>
							<goals>
								<goal>jar-no-fork</goal>
							</goals>
							<phase>deploy</phase>							
							<configuration>
								<skipSource>false</skipSource>
								<attach>true</attach>
							</configuration>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>2.8.2</version>
				</plugin>
				<plugin>
					<groupId>com.github.github</groupId>
					<artifactId>site-maven-plugin</artifactId>
					<version>0.12</version>
					<configuration>
						<message>Maven artifacts for ${project.version}</message>
						<noJekyll>true</noJekyll>
						<outputDirectory>${project.build.directory}</outputDirectory>
						<branch>refs/heads/${branch-name}</branch>
						<includes>
							<include>**/*</include>
						</includes>
						<merge>true</merge>
						<repositoryName>BjlSmtp</repositoryName>
						<repositoryOwner>tony-bringardner</repositoryOwner>
						<server>github</server>
					</configuration>
					<executions>
						<execution>
							<goals>
								<goal>site</goal>
							</goals>
							<phase>deploy</phase>
						</execution>
					</executions>
				</plugin>

				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>3.5.2</version>
					<configuration>
						<test><!-- your test suite class name should be here -->
						</test>
					</configuration>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

	<distributionManagement>
		<repository>
			<id>github</id>
			<name>tony-bringardner</name>
			<url>https://maven.pkg.github.com/tony-bringardner/BjlSmtp</url>
		</repository>

	</distributionManagement>

	<url>http://bringardner.us/BJL/BjlSmtp</url>
	<inceptionYear>2026</inceptionYear>

	<dependencies>
		<dependency>
  			<groupId>us.bringardner</groupId>
  			<artifactId>bjl_net_framework</artifactId>
  			<version>0.1.1</version>
		</dependency>
		<dependency>
  			<groupId>us.bringardner</groupId>
  			<artifactId>bjl_file_system</artifactId>
  			<version>0.1.1</version>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<version>5.9.1</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-suite-engine</artifactId>
			<version>1.9.1</version>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
